# Generated by Django 6.0.3 on 2026-03-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assignment_mode', models.CharField(choices=[('shared', 'Umumiy (barcha uchun bir xil)'), ('individual', 'Individual (har userga alohida)')], default='individual', max_length=20)),
                ('tokens_file', models.FileField(upload_to='datasets/tokens/')),
                ('suffix_file', models.FileField(upload_to='datasets/suffixes/')),
                ('is_active', models.BooleanField(default=False)),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tokenassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenassignment',
            name='mode',
            field=models.CharField(choices=[('shared', 'Umumiy (barcha uchun bir xil)'), ('individual', 'Individual (har userga alohida)')], default='individual', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tokenassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.datasetconfig'),
        ),
        migrations.AddField(
            model_name='tokenassignment',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='annotator.datasetconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenassignment',
            unique_together={('dataset', 'user', 'token_index', 'mode')},
        ),
        migrations.CreateModel(
            name='ConsensusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_index', models.IntegerField(db_index=True)),
                ('word', models.CharField(max_length=255)),
                ('action', models.CharField(default='save', max_length=10)),
                ('segments', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('subtypes', models.JSONField(default=list)),
                ('codes', models.JSONField(default=list)),
                ('vote_count', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_results', to='annotator.datasetconfig')),
            ],
            options={
                'ordering': ['token_index'],
                'unique_together': {('dataset', 'token_index')},
            },
        ),
    ]
