# Generated by Django 6.0.3 on 2026-03-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_alter_user_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsensusResult',
        ),
    ]
