# Generated by Django 6.0.3 on 2026-03-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_delete_consensusresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.tokenassignment'),
        ),
    ]
